kind: Deployment
metadata:
  name: relay-server
  namespace: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-server
  template:
    metadata:
      labels:
        app: relay-server
    spec:
      containers:
        - name: relay-server
          image: vishnu827/relay-server:latest
          env:
            - name: CLIENT_ORIGIN
              value: http://localhost:8080
            - name: EXTRA_ORIGINS
              value: http://localhost:5173,http://relay-client.local
          envFrom:
            - secretRef:
                name: relay-secrets
          ports:
            - containerPort: 5000
