apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-frontend
  namespace: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-frontend
  template:
    metadata:
      labels:
        app: relay-frontend
    spec:
      containers:
        - name: relay-frontend
          image: vishnuvardhanreddy/chat-frontend:v1
          ports:
            - containerPort: 5173