kind: Deployment
metadata:
  name: relay-server
  namespace: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-server
  template:
    metadata:
      labels:
        app: relay-server
    spec:
      containers:
        - name: relay-server
          image: vishnu827/relay-server:latest
          envFrom:
            - secretRef:
                name: relay-secrets
          ports:
            - containerPort: 5000